In [3]:
import numpy as np
empty_array = np.empty((2, 2))
print("Empty Array (2x2):")
print(empty_array)

ones_array = np.ones((4, 2))
print("\nAll Ones Array:")
print(ones_array)

shape = (3, 3)
fill_value = 7
filled_array = np.full(shape, fill_value)
print("\nFilled Array (3x3) with value 7:")
print(filled_array)

reference_array = np.array([[1, 2], [3, 4]])
zeros_like_array = np.zeros_like(reference_array)
print("\nZeros Like Array:")
print(zeros_like_array)


ones_like_array = np.ones_like(reference_array)
print("\nOnes Like Array:")
print(ones_like_array)

new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("\nNumpy Array from List:")
print(numpy_array)


Empty Array (2x2):
[[5.e-324 4.e-323]
 [4.e-323 4.e-323]]

All Ones Array:
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Filled Array (3x3) with value 7:
[[7 7 7]
 [7 7 7]
 [7 7 7]]

Zeros Like Array:
[[0 0]
 [0 0]]

Ones Like Array:
[[1 1]
 [1 1]]

Numpy Array from List:
[1 2 3 4]


In [5]:
array_10_49 = np.arange(10, 50)
print("Array from 10 to 49:")
print(array_10_49)

Array from 10 to 49:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [7]:
matrix_3x3 = np.arange(9).reshape(3, 3)
print("\n3X3 Matrix with values ranging from 0 to 8:")
print(matrix_3x3)



3X3 Matrix with values ranging from 0 to 8:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [9]:
identity_matrix = np.eye(3)
print("\n3X3 Identity Matrix:")
print(identity_matrix)


3X3 Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
random_array = np.random.random(30)
mean_random_array = random_array.mean()
print("\nRandom Array of size 30:")
print(random_array)
print("Mean of Random Array:", mean_random_array)


Random Array of size 30:
[0.65081863 0.36436728 0.47346413 0.49228813 0.43743237 0.09265019
 0.15476102 0.53244988 0.58451092 0.85532077 0.18670672 0.46335236
 0.73979371 0.97035995 0.67061839 0.73888445 0.13458236 0.67301455
 0.97285673 0.11446048 0.35154962 0.31852285 0.10317432 0.37614372
 0.93013128 0.84073108 0.16320245 0.35994912 0.67390169 0.51653966]
Mean of Random Array: 0.497884626467226


In [13]:
random_10x10 = np.random.random((10, 10))
min_value = random_10x10.min()
max_value = random_10x10.max()
print("\n10X10 Random Array:")
print(random_10x10)
print("Minimum Value:", min_value)
print("Maximum Value:", max_value)


10X10 Random Array:
[[0.03336425 0.18094798 0.05012348 0.54677883 0.95751178 0.11759219
  0.0809369  0.24687481 0.63941862 0.5375404 ]
 [0.90571185 0.89269526 0.81816163 0.89980099 0.80391871 0.55489457
  0.71909664 0.89509704 0.69038665 0.01187533]
 [0.5386454  0.82720984 0.82821262 0.651181   0.85044538 0.14663853
  0.12214686 0.37883874 0.43234914 0.86060167]
 [0.50562012 0.13492157 0.46824946 0.98070668 0.5174245  0.87609495
  0.29355109 0.22914018 0.25733334 0.1258551 ]
 [0.29666056 0.72833844 0.68634627 0.26566122 0.01283976 0.02262658
  0.85727713 0.75560456 0.41738033 0.47008153]
 [0.1466291  0.70043993 0.15780487 0.14272997 0.02575019 0.63394258
  0.02725138 0.30848322 0.63917632 0.4119987 ]
 [0.78186133 0.19689488 0.26242074 0.71884799 0.94112099 0.8681703
  0.58171516 0.71347614 0.1391196  0.9272772 ]
 [0.88018294 0.11997405 0.72855236 0.68422048 0.97092278 0.3267028
  0.25622378 0.49108743 0.75388473 0.29680796]
 [0.63788896 0.17986439 0.61105693 0.35532216 0.58725792 0.29

In [15]:
zero_array = np.zeros(10)
zero_array[4] = 1  # 5th element (index 4) is replaced with 1
print("\nZero Array with 5th element replaced with 1:")
print(zero_array)


Zero Array with 5th element replaced with 1:
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [17]:
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("\nReversed Array:")
print(reversed_arr)


Reversed Array:
[0 4 0 0 2 1]


In [19]:
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("\n2D Array with 1 on border and 0 inside:")
print(border_array)


2D Array with 1 on border and 0 inside:
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [21]:
checkerboard_pattern = np.zeros((8, 8))
checkerboard_pattern[1::2, ::2] = 1
checkerboard_pattern[::2, 1::2] = 1
print("\n8X8 Checkerboard Pattern:")
print(checkerboard_pattern)


8X8 Checkerboard Pattern:
[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [23]:
import numpy as np

# Defining arrays v, w, x, and y
v = np.array([1, 2, 3])
w = np.array([4, 5, 6])
x = np.array([7, 8, 9])
y = np.array([10, 11, 12])

# 1. Add the two arrays
sum_array = v + w
print("Sum of v and w:")
print(sum_array)

# 2. Subtract the two arrays
difference_array = v - w
print("\nDifference of v and w:")
print(difference_array)

# 3. Multiply the array with any integer (let's choose 2)
multiplied_array = v * 2
print("\nArray v multiplied by 2:")
print(multiplied_array)

# 4. Find the square of each element of the array
squared_array = np.square(v)
print("\nSquare of each element of v:")
print(squared_array)

# 5. Find the dot product between: v and w; x and v; x and y
dot_v_w = np.dot(v, w)
dot_x_v = np.dot(x, v)
dot_x_y = np.dot(x, y)
print("\nDot Product between v and w:", dot_v_w)
print("Dot Product between x and v:", dot_x_v)
print("Dot Product between x and y:", dot_x_y)

# 6. Concatenate x and y along rows and concatenate v and w along columns
concat_x_y = np.concatenate((x, y), axis=0) 
concat_v_w = np.concatenate((v.reshape(-1, 1), w.reshape(-1, 1)), axis=1) 
print("\nConcatenate x and y along row:")
print(concat_x_y)
print("\nConcatenate v and w along column:")
print(concat_v_w)

# 7. Concatenate x and v; if you get an error, observe and explain why did you get the error?
try:
    concat_x_v = np.concatenate((x, v), axis=0) 
    print("\nConcatenate x and v along row:")
    print(concat_x_v)
except ValueError as e:
    print("\nError when trying to concatenate x and v along row:")
    print(e)


Sum of v and w:
[5 7 9]

Difference of v and w:
[-3 -3 -3]

Array v multiplied by 2:
[2 4 6]

Square of each element of v:
[1 4 9]

Dot Product between v and w: 32
Dot Product between x and v: 50
Dot Product between x and y: 266

Concatenate x and y along row:
[ 7  8  9 10 11 12]

Concatenate v and w along column:
[[1 4]
 [2 5]
 [3 6]]

Concatenate x and v along row:
[7 8 9 1 2 3]


In [25]:

A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A * A^-1 = I (Identity matrix)
A_inv = np.linalg.inv(A)  # Calculate the inverse of A
I = np.identity(2)  # Identity matrix of size 2x2
result_A_inv = np.dot(A, A_inv)  # A * A^-1

print("A * A^-1 (should be identity matrix I):")
print(result_A_inv)
print("Identity matrix I:")
print(I)

# 2. Prove AB != BA
AB = np.dot(A, B)  # Matrix multiplication AB
BA = np.dot(B, A)  # Matrix multiplication BA

print("\nAB:")
print(AB)
print("\nBA:")
print(BA)
print("\nIs AB equal to BA? ", np.array_equal(AB, BA))

# 3. Prove (AB)^T = B^T * A^T
AB_T = np.transpose(AB)  # Transpose of AB
B_T = np.transpose(B)  # Transpose of B
A_T = np.transpose(A)  # Transpose of A
B_T_A_T = np.dot(B_T, A_T)  # B^T * A^T

print("\n(AB)^T:")
print(AB_T)
print("\nB^T * A^T:")
print(B_T_A_T)
print("\nIs (AB)^T equal to B^T * A^T? ", np.array_equal(AB_T, B_T_A_T))


A * A^-1 (should be identity matrix I):
[[1.0000000e+00 4.4408921e-16]
 [0.0000000e+00 1.0000000e+00]]
Identity matrix I:
[[1. 0.]
 [0. 1.]]

AB:
[[23 13]
 [51 29]]

BA:
[[36 44]
 [13 16]]

Is AB equal to BA?  False

(AB)^T:
[[23 51]
 [13 29]]

B^T * A^T:
[[23 51]
 [13 29]]

Is (AB)^T equal to B^T * A^T?  True


In [27]:
import numpy as np

# Coefficient matrix A
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

# Constants matrix B
B = np.array([[-1],
              [-3],
              [9]])

# Calculate the inverse of A
A_inv = np.linalg.inv(A)

# Calculate the solution X
X = np.dot(A_inv, B)

print("Solution for x, y, z:")
print(X)


Solution for x, y, z:
[[ 2.]
 [ 1.]
 [-2.]]


In [29]:
import time
import numpy as np

# Creating two lists of size 1,000,000
list1 = [i for i in range(1, 1000001)]
list2 = [i for i in range(1, 1000001)]

start_time = time.time()
list_sum = [x + y for x, y in zip(list1, list2)]
list_time = time.time() - start_time

array1 = np.array(list1)
array2 = np.array(list2)

start_time = time.time()
array_sum = array1 + array2
array_time = time.time() - start_time

# Printing the time taken for each operation
print(f"Time taken using Python Lists: {list_time} seconds")
print(f"Time taken using NumPy Arrays: {array_time} seconds")


Time taken using Python Lists: 0.08156919479370117 seconds
Time taken using NumPy Arrays: 0.0 seconds


In [64]:
import time
import numpy as np

# Creating two lists of size 1,000,000
list1 = [i for i in range(1, 1000001)]
list2 = [i for i in range(1, 1000001)]

start_time = time.time()
list_multiply = [x * y for x, y in zip(list1, list2)]
list_multiply_time = time.time() - start_time
array1 = np.array(list1)
array2 = np.array(list2)

start_time = time.time()
array_multiply = array1 * array2
array_multiply_time = time.time() - start_time

# Printing the time taken for each operation
print(f"Time taken using Python Lists: {list_multiply_time} seconds")
print(f"Time taken using NumPy Arrays: {array_multiply_time} seconds")


Time taken using Python Lists: 0.5631837844848633 seconds
Time taken using NumPy Arrays: 0.005000591278076172 seconds


In [51]:
import time
import numpy as np

# Creating two lists of size 1,000,000
list1 = [i for i in range(1, 1000001)]
list2 = [i for i in range(1, 1000001)]

# Dot product using Python Lists
start_time = time.time()
dot_product_list = sum(x * y for x, y in zip(list1, list2))
list_time = time.time() - start_time

# Dot product using NumPy Arrays
array1 = np.array(list1)
array2 = np.array(list2)

start_time = time.time()
dot_product_array = np.dot(array1, array2)
array_time = time.time() - start_time

# Printing the time taken for each operation
print(f"Time taken using Python Lists: {list_time} seconds")
print(f"Time taken using NumPy Arrays: {array_time} seconds")


Time taken using Python Lists: 0.20411109924316406 seconds
Time taken using NumPy Arrays: 0.0 seconds


In [63]:
import time
import numpy as np

# Creating two 1000x1000 matrices using Python lists
matrix1 = [[i for i in range(1000)] for j in range(1000)]
matrix2 = [[i for i in range(1000)] for j in range(1000)]

# Matrix multiplication using Python lists
start_time = time.time()
result_list = [[sum(a * b for a, b in zip(matrix1_row, matrix2_col)) for matrix2_col in zip(*matrix2)] for matrix1_row in matrix1]
list_time = time.time() - start_time

# Matrix multiplication using NumPy arrays
array1 = np.array(matrix1)
array2 = np.array(matrix2)

start_time = time.time()
result_array = np.dot(array1, array2)

array_time = time.time() - start_time

# Printing the time taken for each operation
print(f"Time taken using Python Lists: {list_time} seconds")
print(f"Time taken using NumPy Arrays: {array_time} seconds")


Time taken using Python Lists: 80799.44284248352 seconds
Time taken using NumPy Arrays: 3.1162052154541016 seconds
